DROP TABLE IF EXISTS ai_feedback CASCADE;
DROP TABLE IF EXISTS ai_requests CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS prompts CASCADE;
DROP TABLE IF EXISTS service_metrics CASCADE;
DROP TABLE IF EXISTS users CASCADE;
