-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gigaoffice;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gigaoffice;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO gigaoffice;